Trash_Collector/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Trash_Collector.Models
{
    public class Customer
    {
        [Key]
        public int ID { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }        
        [ForeignKey("Address")]
        public int AddressID { get; set; }
        public Address Address { get; set; }
        [Display(Name = "Total Amount Owed")]
        public double AmountOwed { get; set; }
        [Display(Name = "Weekly Pick Up Day")]
        public DayOfWeek? WeeklyPickupDay { get; set; }
        [Display(Name = "Special Pickup Day")]
        public DateTime? SpecialPickupDay { get; set; }
        [Display(Name = "Pickup Suspension Start Date")]
        public DateTime? PickupPauseDate { get; set; }
        [Display(Name = "Pickup Resuming Date")]
        public DateTime? ResumePickupDate { get; set; }
        [Display (Name = "Last Pickup Day")]
        public DateTime? LastPickupDay { get; set; }
    }
}

Trash_Collector/Controllers/CustomersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Trash_Collector.Models;

namespace Trash_Collector.Controllers
{
    [Authorize(Roles = "Customer")]
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpGet]        
        public ActionResult Create()
        {
            Address address = new Address();
            Customer customer = new Customer();            
            NewCustomerViewModel viewmodel = new NewCustomerViewModel();
            viewmodel.CustomerDetails = customer;
            viewmodel.AddressInformation = address;
            viewmodel.ID = 0;
            return View(viewmodel);
        }
        
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewCustomerViewModel viewmodel)
        {
            string userID = User.Identity.GetUserId();
            var newCustomer = new Customer();            
            newCustomer.Email = db.Users.Where(u => u.Id == userID).Single().Email;
            newCustomer.FirstName = viewmodel.CustomerDetails.FirstName;
            newCustomer.LastName = viewmodel.CustomerDetails.LastName;            
            db.Customers.Add(newCustomer);
            db.Addresses.Add(viewmodel.AddressInformation);            
            db.SaveChanges();
            return RedirectToAction("Index", new { id = newCustomer.ID });            
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,email,password,Address,AmountOwed,WeeklyPickupDay,SpecialPickupDay,PickupPauseDate,ResumePickupDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = customer.ID });
            }
            return View(customer);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = customer.ID });
        }

        public ActionResult WeeklyPickup(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WeeklyPickup(Customer customer)
        {
            var currentCustomer = db.Customers.Where(c => c.ID == customer.ID).Single();
            currentCustomer.WeeklyPickupDay = customer.WeeklyPickupDay;
            db.SaveChanges();
            return RedirectToAction("Index", new { id = currentCustomer.ID });
        }

        public ActionResult SpecialPickup(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SpecialPickup(Customer customer)
        {
            var currentCustomer = db.Customers.Where(c => c.ID == customer.ID).Single();
            currentCustomer.SpecialPickupDay = customer.SpecialPickupDay;
            currentCustomer.AmountOwed += 5.5;
            db.SaveChanges();
            return RedirectToAction("Index", new { id = currentCustomer.ID });
        }

        public ActionResult Billing(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult PauseService(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PauseService(Customer customer)
        {
            var currentCustomer = db.Customers.Where(c => c.ID == customer.ID).Single();
            currentCustomer.PickupPauseDate = customer.PickupPauseDate;
            currentCustomer.ResumePickupDate = customer.ResumePickupDate;
            db.SaveChanges();
            return RedirectToAction("Index", new { id = customer.ID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trash_Collector/Views/Customers/Billing.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "Billing";
}

<h2>Billing</h2>

<div>
    Your Current Monthly Bill: $@Model.AmountOwed
</div>

Trash_Collector/Views/Customers/Create.cshtml
@model Trash_Collector.Models.NewCustomerViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Please Fill Out Your Information</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CustomerDetails.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerDetails.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerDetails.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerDetails.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerDetails.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerDetails.LastName, "", new { @class = "text-danger" })
        </div>
    </div>    
    
    <div class="form-group">
        @Html.LabelFor(model => model.AddressInformation.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressInformation, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.EditorFor(model => model.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Address.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Address.ZipCode, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.AddressInformation.Street, "", new { @class = "text-danger" })
        </div>
    </div>
    @*@Html.HiddenFor(model => model.ID);*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trash_Collector/Views/Customers/Delete.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountOwed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountOwed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeeklyPickupDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeeklyPickupDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialPickupDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialPickupDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PickupPauseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PickupPauseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResumePickupDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResumePickupDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Trash_Collector/Views/Customers/Details.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountOwed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountOwed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeeklyPickupDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeeklyPickupDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialPickupDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialPickupDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PickupPauseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PickupPauseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResumePickupDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResumePickupDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", Model.ID) |
    @Html.ActionLink("Back to List", "Index", Model.ID)
</p>

Trash_Collector/Views/Customers/Edit.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountOwed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountOwed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountOwed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WeeklyPickupDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.WeeklyPickupDay, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WeeklyPickupDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialPickupDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialPickupDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialPickupDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PickupPauseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PickupPauseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PickupPauseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResumePickupDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResumePickupDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResumePickupDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trash_Collector/Views/Customers/Index.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "Index";
}

<div class="jumbotron">
    <h1>Customer Dashboard</h1>
    <p class="lead">Change your weekly pickup, schedule special pickups, pause and resume services and see billing information.</p>    
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Weekly Pickup</h2>
        <p>
            @if (Model.WeeklyPickupDay == null)
            {
                <text><strong>Not Currently Set</strong></text>
            }
            <b>@Model.WeeklyPickupDay</b>
        </p>
        <p><a class="btn btn-default" href="@Url.Action("WeeklyPickUp", "Customers", new { id = Model.ID })">Change Pickup Day &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Special Pickups</h2>
        <p>
            @if (Model.SpecialPickupDay == null)
            {
                <text><strong>No Special Pickups Scheduled ($13 Each)</strong></text>
            }
            else
            {
                <b>@Model.SpecialPickupDay.Value.ToShortDateString()</b>
            }

        </p>
        <p><a class="btn btn-default" href="@Url.Action("SpecialPickup", "Customers", new { id = Model.ID })">Schedule a Pickup &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Billing</h2>
        <p>
            <b>Monthly Balance: $@Model.AmountOwed</b>
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Billing", "Customers", new { id = Model.ID })">Details &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Pause Service</h2>
        <p>
            @if (Model.PickupPauseDate == null)
            {
                <text><strong>No Service Pauses Scheduled</strong></text>
            }
            else
            {
                <text><b>Service Pausing: @Model.PickupPauseDate.Value.ToShortDateString()</b></text>
                <br />
                <text><b>Service Resuming: @Model.ResumePickupDate.Value.ToShortDateString()</b></text>
            }
        </p>
        <p><a class="btn btn-default" href="@Url.Action("PauseService", "Customers", new { id = Model.ID })">Add or Change &raquo;</a></p>
    </div>
</div>

Trash_Collector/Views/Customers/PauseService.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "SpecialPickup";
}

<h2>SpecialPickup</h2>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script>
            $(function () {
                $(".datepicker").datepicker();
            });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PickupPauseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PickupPauseDate, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(model => model.PickupPauseDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ResumePickupDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResumePickupDate, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(model => model.ResumePickupDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", Model.ID)
</div>

Trash_Collector/Views/Customers/SpecialPickup.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "SpecialPickup";
}

<h2>SpecialPickup</h2>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        
        <script>
            $(function () {
                $(".datepicker").datepicker();
            });
        </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SpecialPickupDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialPickupDay, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(model => model.SpecialPickupDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", Model.ID)
</div>

Trash_Collector/Views/Customers/WeeklyPickup.cshtml
@model Trash_Collector.Models.Customer

@{
    ViewBag.Title = "WeeklyPickup";
}

<h2>WeeklyPickupDay</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.WeeklyPickupDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.WeeklyPickupDay, "Monday", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WeeklyPickupDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", Model.ID)
</div>